### ISSUE TITLE
Incomplete booking info

### ISSUE THREAD

**Issue by HeshamMeneisi** [devcurate/coaching#16]
Right now:

```
export interface IBooking {
    id: string;
    eventId: string;
    booker: string;
}
```

The following is the current data required on booking card.

```
:course-title="card.courseTitle"
:course-date="card.courseDate"
:time-start="card.timeStart"
:time-end="card.timeEnd"
:talent="card.talent"
 :img="card.img"

```

Fetching everything by ID is fine but there are a few issues:

1. We don't have talent by id endpoint to get booker data
2. Track is missing

**Comment by cyberhck** [comment]
You're right, coach also won't know what track is that, good catch, I'll fix it :)
