### ISSUE TITLE
Weird response on bookTimeSlot

### ISSUE THREAD

**Issue by HeshamMeneisi** [devcurate/coaching#31]
{"type":"https://tools.ietf.org/html/rfc7231#section-6.5.1","title":"One or more validation errors occurred.","status":400,"traceId":"|343399fe-4a2362d10c12b116.","errors":{"TrackId":["The TrackId field is required."]}}

TrackId isn't required on sdk. When did this get added?

**Comment by cyberhck** [comment]
fixed just now :) use 7.0.1
